.TH CHROOT "1" "ASMR Coreutils" "User Commands"
.SH NAME
chroot \- switches root directory to provided path
.SH SYNOPSIS
.B chroot
\fI\,NEWROOT \/\fR
.br
.SH DESCRIPTION
.PP
switches root directory to provided path
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
chroot(2)
