.TH ECHO "1" "ASMR Coreutils" "User Commands"
.SH NAME
echo \- display a line of text
.SH SYNOPSIS
.B echo
[\fI\,STRING\/\fR]...
.br
.SH DESCRIPTION
.PP
Echo the STRING(s) to standard output.
.PP
NOTE: your shell may have its own version of echo, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
