.TH FALSE "1" "ASMR Coreutils" "User Commands"
.SH NAME
false \- do nothing, unsuccessfully
.SH SYNOPSIS
.B false
.SH DESCRIPTION
.PP
Exit with a status code indicating failure.
.PP
NOTE: your shell may have its own version of false, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
