.TH HOSTNAME "1" "ASMR Coreutils" "User Commands"
.SH NAME
hostname \- show or set system host name
.SH SYNOPSIS
.B hostname
[\fI\,NAME\/\fR]
.SH DESCRIPTION
Show or set the system's host name.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
