.TH MKDIR "1" "ASMR Coreutils" "User Commands"
.SH NAME
mkdir \- make directories
.SH SYNOPSIS
.B mkdir
\fI\,DIRECTORY\/\fR...
.SH DESCRIPTION
.PP
Create the DIRECTORY(ies), if they do not already exist.
.PP
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
mkdir(2)
