.TH READN "1" "ASMR Coreutils" "User Commands"
.SH NAME
readn \- read n bytes from a file.
.SH SYNOPSIS
.B readn
[\fI\,n\/\fR] [\fI\,FILE\/\fR]...
.SH DESCRIPTION
.PP
Read n bytes from FILE(s).
.SH EXAMPLES
.TP
readn 10 file
Output the first 10 bytes of file's contents.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
