.TH RM "1" "ASMR Coreutils" "User Commands"
.SH NAME
rm \- remove files.
.SH SYNOPSIS
.B rm
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
removes each specified file.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
unlink(1), unlink(2)
