.TH RMDIR "1" "ASMR Coreutils" "User Commands"
.SH NAME
rmdir \- remove directories.
.SH SYNOPSIS
.B rmdir
[\fI\,DIR\/\fR]...
.SH DESCRIPTION
removes each specified emtpy directory.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
rmdir(2)
