.TH SLEEP "1" "ASMR Coreutils" "User Commands"
.SH NAME
sleep \- delay for a specified amount of time
.SH SYNOPSIS
.B sleep
[\fI\TIME\/\fR]...
.SH DESCRIPTION
.PP
Pause for TIME time.
.SH EXAMPLES
.TP
sleep 1.5
sleeps for 1.5 seconds.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
