.TH STAT "1" "ASMR Coreutils" "User Commands"
.SH NAME
stat \- display file status
.SH SYNOPSIS
.B stat
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
Display file status.
.PP
NOTE: your shell may have its own version of stat, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
stat(2), statfs(2), statx(2)
