.TH SWAPOFF "1" "ASMR Coreutils" "User Commands"
.SH NAME
swapoff \- tell the system to not use a file as swap
.SH SYNOPSIS
.B swapoff
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
.PP
Tell the system to not use a file as swap
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
