.TH SWAPON "1" "ASMR Coreutils" "User Commands"
.SH NAME
swapon \- tell the system to use a file as swap
.SH SYNOPSIS
.B swapon
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
.PP
Tell the system to use the provided file as swap.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
