.TH SYMLINK "1" "ASMR Coreutils" "User Commands"
.SH NAME
symlink \- call the symlink function to create a link to a file
.SH SYNOPSIS
.B link
\fI\,FILE1 FILE2\/\fR
.SH DESCRIPTION
.PP
Call the link function to create a link named FILE2 to an existing FILE1.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
symlink(2)
