.TH TEE "1" "ASMR Coreutils" "User Commands"
.SH NAME
tee \- read from standard input and write to standard output and files
.SH SYNOPSIS
.B tee
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
Copy standard input to each FILE, or to standard output.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
