.TH TOUCH "1" "ASMR Coreutils" "User Commands"
.SH NAME
touch \- touch file
.SH SYNOPSIS
.B touch
[\fI\,FILE\/\fR]...
.SH DESCRIPTION
A FILE argument that does not exist is created empty.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
