.TH TRUE "1" "ASMR Coreutils" "User Commands"
.SH NAME
true \- do nothing, successfully
.SH SYNOPSIS
.B true
.SH DESCRIPTION
.PP
Exit with a status code indicating successfully.
.PP
NOTE: your shell may have its own version of true, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
