.TH UNLINK "1" "ASMR Coreutils" "User Commands"
.SH NAME
unlink \- call the unlink function to remove a link to a file
.SH SYNOPSIS
.B unlink
[\fI\,FILE1\/\fR]...
.SH DESCRIPTION
.PP
Call the unlink function to remove the name of a file/link.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
.SH "SEE ALSO"
unlink(2)
