.TH YES "1" "ASMR Coreutils" "User Commands"
.SH NAME
yes \- output a string repeatedly until killed
.SH SYNOPSIS
.B yes
[\fI\,STRING\/\fR]...
.br
.B yes
\fI\,OPTION\/\fR
.SH DESCRIPTION
Repeatedly output a line with all specified STRING(s), or 'y'.
.SH AUTHOR
Written by Dan Ahriman von Asteras
.SH "REPORTING BUGS"
Create an issue at the github page: <https://github.com/Genghius/core-asmr>
